In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from scipy.stats import zscore
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
import warnings
warnings.filterwarnings('ignore')
from sklearn import datasets

# Classification- with label as region

In [5]:
d=pd.read_csv('avacado.csv')
d

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1               1  2015-12-20          1.35      54876.98   674.28   44638.81   
2               2  2015-12-13          0.93     118220.22   794.70  109149.67   
3               3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4               4  2015-11-29          1.28      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18244           7  2018-02-04          1.63      17074.83  2046.96    1529.20   
18245           8  2018-01-28          1.71      13888.04  1191.70    3431.50   
18246           9  2018-01-21          1.87      13766.76  1191.92    2452.79   
18247          10  2018-01-14          1.93      16205.22  1527.63    2981.04   
18248          11  2018-01-07          1.62      17489.58  2894.77    2356.13   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18244    0.00    13498.67    13066.82      431.85          0.0       organic   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   

       year            region  
0      2015            Albany  
1      2015            Albany  
2      2015            Albany  
3      2015            Albany  
4      2015            Albany  
...     ...               ...  
18244  2018  WestTexNewMexico  
18245  2018  WestTexNewMexico  
18246  2018  WestTexNewMexico  
18247  2018  WestTexNewMexico  
18248  2018  WestTexNewMexico  

[18249 rows x 14 columns]

In [6]:
df=pd.DataFrame(d)
df

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1               1  2015-12-20          1.35      54876.98   674.28   44638.81   
2               2  2015-12-13          0.93     118220.22   794.70  109149.67   
3               3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4               4  2015-11-29          1.28      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18244           7  2018-02-04          1.63      17074.83  2046.96    1529.20   
18245           8  2018-01-28          1.71      13888.04  1191.70    3431.50   
18246           9  2018-01-21          1.87      13766.76  1191.92    2452.79   
18247          10  2018-01-14          1.93      16205.22  1527.63    2981.04   
18248          11  2018-01-07          1.62      17489.58  2894.77    2356.13   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18244    0.00    13498.67    13066.82      431.85          0.0       organic   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   

       year            region  
0      2015            Albany  
1      2015            Albany  
2      2015            Albany  
3      2015            Albany  
4      2015            Albany  
...     ...               ...  
18244  2018  WestTexNewMexico  
18245  2018  WestTexNewMexico  
18246  2018  WestTexNewMexico  
18247  2018  WestTexNewMexico  
18248  2018  WestTexNewMexico  

[18249 rows x 14 columns]

In [7]:
df.isnull().sum()

Unnamed: 0      0
Date            0
AveragePrice    0
Total Volume    0
4046            0
4225            0
4770            0
Total Bags      0
Small Bags      0
Large Bags      0
XLarge Bags     0
type            0
year            0
region          0
dtype: int64

In [8]:
df.dtypes

Unnamed: 0        int64
Date             object
AveragePrice    float64
Total Volume    float64
4046            float64
4225            float64
4770            float64
Total Bags      float64
Small Bags      float64
Large Bags      float64
XLarge Bags     float64
type             object
year              int64
region           object
dtype: object

In [9]:
dfcor=df.corr()
dfcor

Unnamed: 0  AveragePrice  Total Volume      4046      4225  \
Unnamed: 0      1.000000     -0.133008      0.014035  0.017628  0.019829   
AveragePrice   -0.133008      1.000000     -0.192752 -0.208317 -0.172928   
Total Volume    0.014035     -0.192752      1.000000  0.977863  0.974181   
4046            0.017628     -0.208317      0.977863  1.000000  0.926110   
4225            0.019829     -0.172928      0.974181  0.926110  1.000000   
4770            0.041752     -0.179446      0.872202  0.833389  0.887855   
Total Bags     -0.002219     -0.177088      0.963047  0.920057  0.905787   
Small Bags      0.000347     -0.174730      0.967238  0.925280  0.916031   
Large Bags     -0.009196     -0.172940      0.880640  0.838645  0.810015   
XLarge Bags    -0.011546     -0.117592      0.747157  0.699377  0.688809   
year           -0.171667      0.093197      0.017193  0.003353 -0.009559   

                  4770  Total Bags  Small Bags  Large Bags  XLarge Bags  \
Unnamed: 0    0.041752   -0.002219    0.000347   -0.009196    -0.011546   
AveragePrice -0.179446   -0.177088   -0.174730   -0.172940    -0.117592   
Total Volume  0.872202    0.963047    0.967238    0.880640     0.747157   
4046          0.833389    0.920057    0.925280    0.838645     0.699377   
4225          0.887855    0.905787    0.916031    0.810015     0.688809   
4770          1.000000    0.792314    0.802733    0.698471     0.679861   
Total Bags    0.792314    1.000000    0.994335    0.943009     0.804233   
Small Bags    0.802733    0.994335    1.000000    0.902589     0.806845   
Large Bags    0.698471    0.943009    0.902589    1.000000     0.710858   
XLarge Bags   0.679861    0.804233    0.806845    0.710858     1.000000   
year         -0.036531    0.071552    0.063915    0.087891     0.081033   

                  year  
Unnamed: 0   -0.171667  
AveragePrice  0.093197  
Total Volume  0.017193  
4046          0.003353  
4225         -0.009559  
4770         -0.036531  
Total Bags    0.071552  
Small Bags    0.063915  
Large Bags    0.087891  
XLarge Bags   0.081033  
year          1.000000

In [10]:
df.describe()

Unnamed: 0  AveragePrice  Total Volume          4046          4225  \
count  18249.000000  18249.000000  1.824900e+04  1.824900e+04  1.824900e+04   
mean      24.232232      1.405978  8.506440e+05  2.930084e+05  2.951546e+05   
std       15.481045      0.402677  3.453545e+06  1.264989e+06  1.204120e+06   
min        0.000000      0.440000  8.456000e+01  0.000000e+00  0.000000e+00   
25%       10.000000      1.100000  1.083858e+04  8.540700e+02  3.008780e+03   
50%       24.000000      1.370000  1.073768e+05  8.645300e+03  2.906102e+04   
75%       38.000000      1.660000  4.329623e+05  1.110202e+05  1.502069e+05   
max       52.000000      3.250000  6.250565e+07  2.274362e+07  2.047057e+07   

               4770    Total Bags    Small Bags    Large Bags    XLarge Bags  \
count  1.824900e+04  1.824900e+04  1.824900e+04  1.824900e+04   18249.000000   
mean   2.283974e+04  2.396392e+05  1.821947e+05  5.433809e+04    3106.426507   
std    1.074641e+05  9.862424e+05  7.461785e+05  2.439660e+05   17692.894652   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00       0.000000   
25%    0.000000e+00  5.088640e+03  2.849420e+03  1.274700e+02       0.000000   
50%    1.849900e+02  3.974383e+04  2.636282e+04  2.647710e+03       0.000000   
75%    6.243420e+03  1.107834e+05  8.333767e+04  2.202925e+04     132.500000   
max    2.546439e+06  1.937313e+07  1.338459e+07  5.719097e+06  551693.650000   

               year  
count  18249.000000  
mean    2016.147899  
std        0.939938  
min     2015.000000  
25%     2015.000000  
50%     2016.000000  
75%     2017.000000  
max     2018.000000

In [11]:
df.skew()

Unnamed: 0       0.108334
AveragePrice     0.580303
Total Volume     9.007687
4046             8.648220
4225             8.942466
4770            10.159396
Total Bags       9.756072
Small Bags       9.540660
Large Bags       9.796455
XLarge Bags     13.139751
year             0.215339
dtype: float64

In [12]:
df.columns

Index(['Unnamed: 0', 'Date', 'AveragePrice', 'Total Volume', '4046', '4225',
       '4770', 'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags', 'type',
       'year', 'region'],
      dtype='object')

In [13]:
df.drop('Date',inplace=True,axis=1)
df.columns

Index(['Unnamed: 0', 'AveragePrice', 'Total Volume', '4046', '4225', '4770',
       'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags', 'type', 'year',
       'region'],
      dtype='object')

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['type']=le.fit_transform(df['type'])
df['region']=le.fit_transform(df['region'])
df

Unnamed: 0  AveragePrice  Total Volume     4046       4225    4770  \
0               0          1.33      64236.62  1036.74   54454.85   48.16   
1               1          1.35      54876.98   674.28   44638.81   58.33   
2               2          0.93     118220.22   794.70  109149.67  130.50   
3               3          1.08      78992.15  1132.00   71976.41   72.58   
4               4          1.28      51039.60   941.48   43838.39   75.78   
...           ...           ...           ...      ...        ...     ...   
18244           7          1.63      17074.83  2046.96    1529.20    0.00   
18245           8          1.71      13888.04  1191.70    3431.50    0.00   
18246           9          1.87      13766.76  1191.92    2452.79  727.94   
18247          10          1.93      16205.22  1527.63    2981.04  727.01   
18248          11          1.62      17489.58  2894.77    2356.13  224.53   

       Total Bags  Small Bags  Large Bags  XLarge Bags  type  year  region  
0         8696.87     8603.62       93.25          0.0     0  2015       0  
1         9505.56     9408.07       97.49          0.0     0  2015       0  
2         8145.35     8042.21      103.14          0.0     0  2015       0  
3         5811.16     5677.40      133.76          0.0     0  2015       0  
4         6183.95     5986.26      197.69          0.0     0  2015       0  
...           ...         ...         ...          ...   ...   ...     ...  
18244    13498.67    13066.82      431.85          0.0     1  2018      53  
18245     9264.84     8940.04      324.80          0.0     1  2018      53  
18246     9394.11     9351.80       42.31          0.0     1  2018      53  
18247    10969.54    10919.54       50.00          0.0     1  2018      53  
18248    12014.15    11988.14       26.01          0.0     1  2018      53  

[18249 rows x 13 columns]

In [15]:
for col in df.columns:
    if df.skew().loc[col]>0.55:
        df[col]=np.log1p(df[col])

In [16]:
df.skew()

Unnamed: 0      0.108334
AveragePrice    0.138629
Total Volume    0.088098
4046           -0.328195
4225           -0.486654
4770            0.099986
Total Bags     -0.218874
Small Bags     -0.622148
Large Bags     -0.547765
XLarge Bags     1.176494
type            0.000329
year            0.215339
region          0.000030
dtype: float64

In [17]:
from scipy.stats import zscore
z=np.abs(zscore(df))
df_new=df[(z<3).all(axis=1)]
df_new

Unnamed: 0  AveragePrice  Total Volume      4046       4225      4770  \
0               0      0.845868     11.070344  6.944801  10.905146  3.895080   
1               1      0.854415     10.912867  6.515127  10.706381  4.083115   
2               2      0.657520     11.680313  6.679222  11.600485  4.879007   
3               3      0.732368     11.277116  7.032624  11.184108  4.298373   
4               4      0.824175     10.840377  6.848515  10.688288  4.340944   
...           ...           ...           ...       ...        ...       ...   
18244           7      0.966984      9.745419  7.624599   7.333154  0.000000   
18245           8      0.996949      9.538855  7.083975   8.141044  0.000000   
18246           9      1.054312      9.530085  7.084159   7.805389  6.591591   
18247          10      1.075002      9.693150  7.332127   8.000363  6.590315   
18248          11      0.963174      9.769418  7.971006   7.765200  5.418453   

       Total Bags  Small Bags  Large Bags  XLarge Bags  type  year  region  
0        9.070833    9.060055    4.545951          0.0     0  2015       0  
1        9.159737    9.149429    4.589955          0.0     0  2015       0  
2        9.005325    8.992584    4.645736          0.0     0  2015       0  
3        8.667708    8.644425    4.903495          0.0     0  2015       0  
4        8.729874    8.697389    5.291746          0.0     0  2015       0  
...           ...         ...         ...          ...   ...   ...     ...  
18244    9.510421    9.477908    6.070391          0.0     1  2018      53  
18245    9.134090    9.098407    5.786284          0.0     1  2018      53  
18246    9.147945    9.143431    3.768384          0.0     1  2018      53  
18247    9.302969    9.298401    3.931826          0.0     1  2018      53  
18248    9.393924    9.391757    3.296207          0.0     1  2018      53  

[17928 rows x 13 columns]

In [18]:
x=df_new.iloc[:,:-1]
print(x)

       Unnamed: 0  AveragePrice  Total Volume      4046       4225      4770  \
0               0      0.845868     11.070344  6.944801  10.905146  3.895080   
1               1      0.854415     10.912867  6.515127  10.706381  4.083115   
2               2      0.657520     11.680313  6.679222  11.600485  4.879007   
3               3      0.732368     11.277116  7.032624  11.184108  4.298373   
4               4      0.824175     10.840377  6.848515  10.688288  4.340944   
...           ...           ...           ...       ...        ...       ...   
18244           7      0.966984      9.745419  7.624599   7.333154  0.000000   
18245           8      0.996949      9.538855  7.083975   8.141044  0.000000   
18246           9      1.054312      9.530085  7.084159   7.805389  6.591591   
18247          10      1.075002      9.693150  7.332127   8.000363  6.590315   
18248          11      0.963174      9.769418  7.971006   7.765200  5.418453   

       Total Bags  Small Bags  Large Ba

In [19]:
y=df_new.iloc[:,-1]
y

0         0
1         0
2         0
3         0
4         0
         ..
18244    53
18245    53
18246    53
18247    53
18248    53
Name: region, Length: 17928, dtype: int32

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=42)

In [21]:
model=MultinomialNB(),SVC(),DecisionTreeClassifier()
for m in model:
    m.fit(x_train,y_train)
    m.score(x_train,y_train)
    predm=m.predict(x_test)
    print('Accuracy score of',m,'is:')
    print(accuracy_score(y_test,predm))
    print(confusion_matrix(y_test,predm))
    print(classification_report(y_test,predm))
    print('\n')

Accuracy score of MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True) is:
0.03751584283903676
[[ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  7]
 [ 0  0  1 ...  1  0  0]
 ...
 [ 0  0  0 ... 32  6  0]
 [ 0  0  0 ... 45  0  4]
 [ 4  0  0 ...  8  8  4]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        84
           1       0.00      0.00      0.00        62
           2       0.03      0.01      0.02        82
           3       0.00      0.00      0.00        72
           4       0.00      0.00      0.00        74
           5       0.01      0.01      0.01        77
           6       0.00      0.00      0.00        81
           7       0.06      0.09      0.07        68
           8       0.00      0.00      0.00        74
           9       0.00      0.00      0.00        82
          10       0.00      0.00      0.00        82
          11       0.00      0.00      0.00        79
          12       0.07      0.32      0

In [22]:
from sklearn.model_selection import cross_val_score
dt=DecisionTreeClassifier()
dtc=dt.fit(x_train,y_train)
print(dtc.score(x_train,y_train))

print('Mean cross_val_score is=',cross_val_score(dt,x,y,cv=10).mean())
print('STD cross_val_score is=',cross_val_score(dt,x,y,cv=10).std())

1.0
Mean cross_val_score is= 0.629594868937074
STD cross_val_score is= 0.06455947128575046



# Regression-with label as avg price

In [23]:
x=df_new.iloc[:,2:]
x

Total Volume      4046       4225      4770  Total Bags  Small Bags  \
0         11.070344  6.944801  10.905146  3.895080    9.070833    9.060055   
1         10.912867  6.515127  10.706381  4.083115    9.159737    9.149429   
2         11.680313  6.679222  11.600485  4.879007    9.005325    8.992584   
3         11.277116  7.032624  11.184108  4.298373    8.667708    8.644425   
4         10.840377  6.848515  10.688288  4.340944    8.729874    8.697389   
...             ...       ...        ...       ...         ...         ...   
18244      9.745419  7.624599   7.333154  0.000000    9.510421    9.477908   
18245      9.538855  7.083975   8.141044  0.000000    9.134090    9.098407   
18246      9.530085  7.084159   7.805389  6.591591    9.147945    9.143431   
18247      9.693150  7.332127   8.000363  6.590315    9.302969    9.298401   
18248      9.769418  7.971006   7.765200  5.418453    9.393924    9.391757   

       Large Bags  XLarge Bags  type  year  region  
0        4.545951          0.0     0  2015       0  
1        4.589955          0.0     0  2015       0  
2        4.645736          0.0     0  2015       0  
3        4.903495          0.0     0  2015       0  
4        5.291746          0.0     0  2015       0  
...           ...          ...   ...   ...     ...  
18244    6.070391          0.0     1  2018      53  
18245    5.786284          0.0     1  2018      53  
18246    3.768384          0.0     1  2018      53  
18247    3.931826          0.0     1  2018      53  
18248    3.296207          0.0     1  2018      53  

[17928 rows x 11 columns]

In [24]:
y=df_new.iloc[:,1]
y

0        0.845868
1        0.854415
2        0.657520
3        0.732368
4        0.824175
           ...   
18244    0.966984
18245    0.996949
18246    1.054312
18247    1.075002
18248    0.963174
Name: AveragePrice, Length: 17928, dtype: float64

In [25]:
def maxr2_score(regr,x,y):
    max_r_score=0
    for r_state in range(42,100):
        x_train, x_test,y_train,y_test=train_test_split(x,y,random_state=r_state,test_size=.20)
        regr.fit(x_train,y_train)
        y_pred=regr.predict(x_test)
        r2_scr=r2_score(y_test,y_pred)
        print('r2 score corresponding to ',r_state,'is',r2_scr)
        if r2_scr>max_r_score:
            max_r_score=r2_scr
            final_r_state=r_state
        
    print('max r2_score corresponding to',final_r_state,'is',max_r_score)
    return final_r_state

In [26]:
lreg=LinearRegression()
maxr2_score(lreg,x,y)

r2 score corresponding to  42 is 0.5444546170364707
r2 score corresponding to  43 is 0.5434408659299506
r2 score corresponding to  44 is 0.5399690071424065
r2 score corresponding to  45 is 0.5351363251345285
r2 score corresponding to  46 is 0.5395441718988506
r2 score corresponding to  47 is 0.5353898930648202
r2 score corresponding to  48 is 0.535827044680883
r2 score corresponding to  49 is 0.5369196681792239
r2 score corresponding to  50 is 0.5291423964845756
r2 score corresponding to  51 is 0.5285481190389887
r2 score corresponding to  52 is 0.5370329533601712
r2 score corresponding to  53 is 0.5403658353251035
r2 score corresponding to  54 is 0.5429724090544883
r2 score corresponding to  55 is 0.5319992511201188
r2 score corresponding to  56 is 0.5328025327083334
r2 score corresponding to  57 is 0.5325719925977195
r2 score corresponding to  58 is 0.5426220993478255
r2 score corresponding to  59 is 0.5229747172108461
r2 score corresponding to  60 is 0.5513759331818934
r2 score corr

92

In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
neighbors={'n_neighbors':range(1,30)}
knr=KNeighborsRegressor()
gknr=GridSearchCV(knr,neighbors,cv=10)
gknr.fit(x,y)
gknr.best_params_

{'n_neighbors': 13}

In [28]:
knr=KNeighborsRegressor(n_neighbors=13)
r_state=maxr2_score(knr,x,y)

r2 score corresponding to  42 is 0.8007611320254505
r2 score corresponding to  43 is 0.7916113399039042
r2 score corresponding to  44 is 0.8007082688923007
r2 score corresponding to  45 is 0.8048585078082978
r2 score corresponding to  46 is 0.7890689820923968
r2 score corresponding to  47 is 0.7943395611202947
r2 score corresponding to  48 is 0.7924886369495879
r2 score corresponding to  49 is 0.7962901438095731
r2 score corresponding to  50 is 0.7891993304006113
r2 score corresponding to  51 is 0.791735595078532
r2 score corresponding to  52 is 0.7884248088952506
r2 score corresponding to  53 is 0.7904756594065825
r2 score corresponding to  54 is 0.7895159469617932
r2 score corresponding to  55 is 0.7842526196423799
r2 score corresponding to  56 is 0.7936427459180718
r2 score corresponding to  57 is 0.7978774560265252
r2 score corresponding to  58 is 0.7982803750230011
r2 score corresponding to  59 is 0.7894777087684677
r2 score corresponding to  60 is 0.8026222694246298
r2 score corr

In [29]:
from sklearn.linear_model import Lasso
lsreg=Lasso()
parameters={'alpha':[0.001,0.01,0.1,1]}
clf=GridSearchCV(lsreg,parameters,cv=10)
clf.fit(x,y)
clf.best_params_

{'alpha': 0.001}

In [30]:
lsreg=Lasso(alpha=0.001)
r_state=maxr2_score(lsreg,x,y)

r2 score corresponding to  42 is 0.5431739913880073
r2 score corresponding to  43 is 0.5423599593136386
r2 score corresponding to  44 is 0.5395967018701844
r2 score corresponding to  45 is 0.5336269954264774
r2 score corresponding to  46 is 0.5387539497974947
r2 score corresponding to  47 is 0.5344861437161752
r2 score corresponding to  48 is 0.5334515915321556
r2 score corresponding to  49 is 0.5360424044524352
r2 score corresponding to  50 is 0.5282950887988346
r2 score corresponding to  51 is 0.5273899676206103
r2 score corresponding to  52 is 0.5348514920995818
r2 score corresponding to  53 is 0.5383135722773323
r2 score corresponding to  54 is 0.5416927003916754
r2 score corresponding to  55 is 0.5309571528284476
r2 score corresponding to  56 is 0.5330537316351419
r2 score corresponding to  57 is 0.5315554498955024
r2 score corresponding to  58 is 0.5419647563072685
r2 score corresponding to  59 is 0.5230624047260537
r2 score corresponding to  60 is 0.5500884607202928
r2 score cor

In [31]:
from sklearn.model_selection import cross_val_score


print ('mean of KNN regressor is',cross_val_score(knr,x,y,cv=5,scoring='r2').mean())
print ('std deviation of the knn regressor is ',cross_val_score(knr,x,y,cv=5,scoring='r2').std())

mean of KNN regressor is 0.08526716612687073
std deviation of the knn regressor is  0.3501214105276888


In [ ]:
from sklearn.externals import joblib
joblib.dump(knr,'Project_8.pkl')