In [1]:
#Example of single document
#without stopwords

from sklearn.feature_extraction.text import CountVectorizer

from nltk.corpus import stopwords
import pandas as pd

#single document (',' seperates each document)
string=['This is an example of bag of words']

#this sep willl convert text into tokens
vect1=CountVectorizer()

vect1.fit_transform(string)
print('bag of words:',vect1.get_feature_names())

bag of words: ['an', 'bag', 'example', 'is', 'of', 'this', 'words']


In [2]:
vect1.vocabulary_

{'this': 5, 'is': 3, 'an': 0, 'example': 2, 'of': 4, 'bag': 1, 'words': 6}

In [3]:
c_vect=CountVectorizer()
c_vect.fit(string)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [4]:
string2=['lets understand bag']

C_new_vect=c_vect.transform(string2)

print('text present at',C_new_vect.toarray())

#compare with indexes
print("original indexes",vect1.get_feature_names())



text present at [[0 1 0 0 0 0 0]]
original indexes ['an', 'bag', 'example', 'is', 'of', 'this', 'words']


In [5]:
## bag of words using stopwords(you can avoid writing extra steps to remove stopwords)

stop_words=stopwords.words('english')

string=['this is an example of bag of words!']
vect1=CountVectorizer(stop_words=stop_words)
print(vect1)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [6]:
vect1.fit_transform(string)
print("bag of words:", vect1.get_feature_names())
print("vocab:",vect1.vocabulary_)

bag of words: ['bag', 'example', 'words']
vocab: {'example': 1, 'bag': 0, 'words': 2}


In [7]:
#using function
def text_matrix(message, countvect):
    terms_doc=countvect.fit_transform(message)
    return pd.DataFrame(terms_doc.toarray(),columns=countvect.get_feature_names())

In [9]:
message=['We are making progress in Natural Language Processing',
         'We will get there', 'But practice is the only mantra to success']

c_vect=CountVectorizer()
print("below metrix is the Bag of Words approach")
text_matrix(message, c_vect)

below metrix is the Bag of Words approach


are  but  get  in  is  language  making  mantra  natural  only  practice  \
0    1    0    0   1   0         1       1       0        1     0         0   
1    0    0    1   0   0         0       0       0        0     0         0   
2    0    1    0   0   1         0       0       1        0     1         1   

   processing  progress  success  the  there  to  we  will  
0           1         1        0    0      0   0   1     0  
1           0         0        0    0      1   0   1     1  
2           0         0        1    1      0   1   0     0

In [17]:
#n-grams

from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import word_tokenize

string=['this is an example of n-gram!']

vect1=CountVectorizer(ngram_range=(1,1))

vect1.fit_transform(string)

vect2=CountVectorizer(ngram_range=(2,2))
vect2.fit_transform(string)

vect3=CountVectorizer(ngram_range=(3,3))
vect3.fit_transform(string)

vect4=CountVectorizer(ngram_range=(4,4))
vect4.fit_transform(string)

print('1-gram :',vect1.get_feature_names())
print('2-gram:',vect2.get_feature_names())
print('3-gram:',vect3.get_feature_names())
print('4-gram:',vect4.get_feature_names())

1-gram : ['an', 'example', 'gram', 'is', 'of', 'this']
2-gram: ['an example', 'example of', 'is an', 'of gram', 'this is']
3-gram: ['an example of', 'example of gram', 'is an example', 'this is an']
4-gram: ['an example of gram', 'is an example of', 'this is an example']


In [18]:
import numpy as np
np.log2(3)

1.584962500721156

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

import pandas as pd

tfid=TfidfVectorizer(smooth_idf=False)

doc=['This is an example.','We will see how it works.','IDF can be confusing']

doc_vector=tfid.fit_transform(doc)
#print(tfid.get_feature_names())

df=pd.DataFrame(doc_vector.todense(),columns=tfid.get_feature_names())
df

an   be  can  confusing  example       how  idf   is        it       see  \
0  0.5  0.0  0.0        0.0      0.5  0.000000  0.0  0.5  0.000000  0.000000   
1  0.0  0.0  0.0        0.0      0.0  0.408248  0.0  0.0  0.408248  0.408248   
2  0.0  0.5  0.5        0.5      0.0  0.000000  0.5  0.0  0.000000  0.000000   

   this        we      will     works  
0   0.5  0.000000  0.000000  0.000000  
1   0.0  0.408248  0.408248  0.408248  
2   0.0  0.000000  0.000000  0.000000

In [22]:
#we will cal the function created earlier
feb_message=['what is that covid','covid is nothing']

tf=TfidfVectorizer()

#passing same message with TF-IDF

text_matrix(feb_message,tf)

covid        is   nothing      that      what
0  0.409937  0.409937  0.000000  0.576152  0.576152
1  0.501549  0.501549  0.704909  0.000000  0.000000

In [23]:
#importance of covid increased based on the occurence and total document
jul_message=['what is that covid covid','covid is bad' ]

text_matrix(jul_message,tf)

bad     covid        is      that      what
0  0.000000  0.668501  0.334251  0.469778  0.469778
1  0.704909  0.501549  0.501549  0.000000  0.000000

In [24]:
from sklearn.feature_extraction.text import  CountVectorizer, TfidfVectorizer

arr=['car was cleaned by jack', 'jack was cleaned by car']

In [25]:
# if you want to take into account just term frequencies:
vectorizer=CountVectorizer(ngram_range=(2,2))

#the ngram range specifies your ngram configuration.

x=vectorizer.fit_transform(arr)

#testing the ngram generation:
print('feature names\n',vectorizer.get_feature_names())

print('array \n',x.toarray())

feature names
 ['by car', 'by jack', 'car was', 'cleaned by', 'jack was', 'was cleaned']
array 
 [[0 1 1 1 0 1]
 [1 0 0 1 1 1]]


In [26]:
#and now testing TFIDF vectorizer:
#you can still specify n-grams here:

vectorizer=TfidfVectorizer(ngram_range=(2,2))
x=vectorizer.fit_transform(arr)

#testing the TFIDF value+ngrams:
print(x.toarray())

[[0.         0.57615236 0.57615236 0.40993715 0.         0.40993715]
 [0.57615236 0.         0.         0.40993715 0.57615236 0.40993715]]


In [27]:
#testing TFIDF vectorizer wthout normalization:
#you can still specify n-grams here.
vectorizer=TfidfVectorizer(ngram_range=(2,2),norm=None)

x=vectorizer.fit_transform(arr)

print(x.toarray())

[[0.         1.40546511 1.40546511 1.         0.         1.        ]
 [1.40546511 0.         0.         1.         1.40546511 1.        ]]
